name: Generate Pacman Contribution

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

permissions:
  contents: write

jobs:
  pacman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Pacman animation
        uses: Platane/snk@v3
        with:
          github_user_name: mhmdtmrsid-lab
          outputs: |
            dist/pacman.svg?palette=github-dark&color_pacman=#FFD700
            [![Generate Pacman Contribution](https://github.com/mhmdtmrsid-lab/mhmdtmrsid-lab/actions/workflows/pacman.yml/badge.svg?branch=output&event=workflow_run)](https://github.com/mhmdtmrsid-lab/mhmdtmrsid-lab/actions/workflows/pacman.yml)

      - name: Publish Pacman
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
